### ISSUE TITLE
Errors occured

### ISSUE THREAD

**Issue by sariug** [sariug/MA_Dependencies#1]
# TODO

- [x] CMake install target for bin files and geo files in scenography.

- [ ] Pathfix for non-cave apps.

- [x] Add "start_server/start_cave" to source files for non-cave apps.

- [x] Rename Sources to modules.

**GLFW 3.2**
=============================================
**Problem** : 
 ```
 CMake Error at CMakeLists.txt:202 (message):
   The RandR library and headers were not found
 ```

**Solution**: sudo apt-get install xorg-dev libglu1-mesa-dev

**MAGNUM**
=============================================
**Problem** :SDL2 is not found.
**Solution** : Now its also downloaded and built.
